######################################################################
# Automatically generated by qmake (2.01a) ? 12? 20 00:21:35 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += iconeditorplugin.hpp
