######################################################################
# Automatically generated by qmake (2.01a) ? 11? 26 15:35:35 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stopwatchdialog.h test.h
FORMS += stopwatchdialog.ui test.ui
SOURCES += main.cpp stopwatchdialog.cpp test.cpp
