######################################################################
# Automatically generated by qmake (2.01a) ? 12? 21 20:45:20 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += monthly_care_plan.hpp one_human.hpp one_service.hpp
FORMS += monthly_care_plan.ui one_human.ui
SOURCES += main.cpp one_service.cpp
