######################################################################
# Automatically generated by qmake (2.01a) ? 12? 21 14:06:17 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . iconeditor iconeditorplugin
INCLUDEPATH += . iconeditor

# Input
HEADERS += care_plan_dialog.hpp \
           iconeditorplugin.hpp \
           one_human.hpp \
           one_service.hpp \
           services.hpp \
           test2.h \
           iconeditor/iconeditor.hpp \
           iconeditorplugin/iconeditorplugin.hpp
FORMS += care_plan_dialog.ui \
         monthly_care_plan.ui \
         one_human.ui \
         one_service.ui \
         select_service_dialog.ui \
         services.ui \
         test2.ui
SOURCES += main.cpp one_service.cpp
