######################################################################
# Automatically generated by qmake (2.01a) ? 12? 20 03:50:56 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . iconeditor iconeditorplugin
INCLUDEPATH += . iconeditor

# Input
HEADERS += iconeditorplugin.hpp \
           test2.h \
           iconeditor/iconeditor.hpp \
           iconeditorplugin/iconeditorplugin.hpp
FORMS += test2.ui
SOURCES += main.cpp
