######################################################################
# Automatically generated by qmake (2.01a) ? 12? 19 23:53:27 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += iconeditor.hpp
